namespace VibeCode.Server.Models;

/// <summary>
/// Represents a user account with authentication credentials
/// </summary>
public class User
{
    public int Id { get; set; }
    
    public string Name { get; set; } = string.Empty;
    
    public string Email { get; set; } = string.Empty;
    
    /// <summary>
    /// Password hash generated by PasswordHasher (PBKDF2-HMAC-SHA256)
    /// Format: AQAAAAIAAYagAAAAE... (includes version + salt + hash)
    /// </summary>
    public string PasswordHash { get; set; } = string.Empty;
    
    public DateTime CreatedAt { get; set; }
    
    public DateTime? UpdatedAt { get; set; }
    
    /// <summary>
    /// Email of admin who created this user
    /// </summary>
    public string? CreatedBy { get; set; }
}
